---
title: "Sesión 2: Matrices, data frames y selección"
output: html_document
---

# Construir tabla a partir de vectores

```r
Pacientes <- c("Juan", "Pepe", "Maria", "Lola", "Luis")
Edad <- c(10, 5, 4, 3, 5)
Temp <- c(36.5, 37, 37.5, 37.3, 37.5)
Analito_B <- c(0.02, 0.05, 0.1, 1.1, 0.0001)
Enfermedad <- c(FALSE, TRUE, TRUE, TRUE, TRUE)
Tipo_enfermedad <- c("Sano", "Flu", "Flu", "Flu", "Anemia")

Kelvin <- Temp + 273
Kelvin
```

# Construir matrices con funcion `cbind` (unir por columna) `rbind` (unir por fila)

```r
mi_tabla <- cbind(Pacientes, Edad, Kelvin, Analito_B, Enfermedad, Tipo_enfermedad)
# Revisar dimensiones. Se despliegan primero filas y luego columnas
dim(mi_tabla)
nrow(mi_tabla)
ncol(mi_tabla)
# Desplegar primeras seis filas o las primeras n
head(mi_tabla)
head(mi_tabla, 25)
# Tipo de tabla (matriz o dataframe)
class(mi_tabla)
```

# Selección de filas y columnas. Se seleccionan de la siguiente forma [filas,columnas]. Se indica el numero de las filas y las columnas que se desean seleccionar


```r
mi_tabla[1:5, 4]
mi_tabla[, 4]
mi_tabla[c(2, 5), 3]
```

# Las matrices solamente pueden contener valores de un solo tipo. Convertimos de matriz a `data.frame` para poder tener columnas con valores de distintos tipos

```r
mi_df <- as.data.frame(mi_tabla)
class(mi_df)
```

# Con un `data.frame` podemos seleccionar columnas de 3 formas distintas

```r
# Indicando el numero de filas, columnas
mi_df[1:5, 2]
# Escribiendo el nombre de la columna o fila como caracter 
mi_df[, "Edad"]
# Indicano la columna con un `$` (esta forma no funciona con matrices)
mi_df$Edad
```

# Se puede convertir el tipo de variable de cada columna y guardala los cambios en el mismo dataframe de la siguiente forma:

```r
# Modifiquemos las columnas de las 3 formas para practicar
mi_df[, 2] <- as.numeric(mi_df[, 2])
mi_df[, "Kelvin"] <- as.numeric(mi_df[, "Kelvin"])
mi_df$Analito_B <- as.numeric(mi_df$Analito_B)
```

# Valores logicos se pueden convertir a numericos y viceversa 

```r
class(mi_df$Enfermedad)
mi_df$Enfermedad <- as.logical(mi_df$Enfermedad)
mi_df$logico_numerico <- as.numeric(mi_df$Enfermedad)
```

# Escencial entender rownames y colnames 

Las funciones `rownames()` y `colnames()` permiten asignar o consultar los nombres de filas y columnas en un `data.frame` o matriz. Esto es útil porque:

- Mejora la legibilidad de los datos.
- Permite seleccionar columnas por nombre en vez de número.
- Hace más claro el resultado de operaciones como filtrado o resumen.

```r
colnames(mi_df)
rownames(mi_df)
```
